DIPLOMA-26: Создать vacancy_item, VacancyAdapter, VacncyViewHolder
lesOlesya/YP-android-diploma-team5 pull request #38
Opened 2024-07-13 10:17 UTC by vvverman

#26

Создал vacancy_item (ещё в 25ой задачке), создал VacancyAdapter, создал VacancyViewHolder

Слушатель нажатий тоже добавил

2024-07-13 18:03 UTC, lesOlesya requested changes

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/values-night/colors.xml
За изменение цвета в ночной и дневной теме отвечает Themes, поэтому в этом файле нет необходимости. Его лучше удалить

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/java/ru/practicum/android/diploma/favourite/ui/VacancyViewHolder.kt
> +            .transform(RoundedCorners(binding.root.resources.getDimensionPixelSize(R.dimen.dp_12)))
.transform(RoundedCorners(12.px))
Чтобы края закруглились в соответствии с дизайном, в RoundedCorners нужно передавать размер в пикселях

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/drawable/logo_plug.xml
> +        android:fillColor="@color/white_black"
android:fillColor="?attr/colorPrimary"

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/layout/item_vacancy.xml
> +    android:layout_height="wrap_content">
android:paddingHorizontal="@dimen/dp_16"
android:paddingVertical="@dimen/dp_8"

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/drawable/vacancy_card.xml
> +    <solid android:color="@color/white" />
solid android:color="?attr/colorPrimary"

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/layout/item_vacancy.xml
> +        android:src="@drawable/logo_plug"
Внутренние расстояния для карточки обычно выставляют в padding(выше написала), поэтому здесь лучше удалить android:layout_marginTop="@dimen/dp_16"

android:src="@drawable/logo_plug" это тоже можно удалить, так как плейсхолдер и так загрузиться глайдом глайдом

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/layout/item_vacancy.xml
> +        android:textSize="@dimen/font_22"
По вышеописанной причине удалить android:layout_marginTop="@dimen/dp_16"

android:fontFamily="@font/ys_display_medium" и android:textSize="@dimen/font_22" заменить на **style="@style/TextMedium22"**

android:textColor="?attr/colorOnPrimary"

2024-07-13 18:03 UTC, lestnitsaKotlin commented on app/src/main/res/layout/item_vacancy.xml
> +        app:layout_constraintTop_toBottomOf="@id/tvVacancyName"
Лучше убрать android:layout_marginStart="@dimen/dp_12", а app:layout_constraintStart_toEndOf="@+id/ivLogo" заменить на **app:layout_constraintStart_toStartOf="@+id/tvVacancyName"**. Так в случае, если нужно будет надписи отодвинуть подальше от лого, расстояние придётся менять только у заголовка

android:fontFamily="@font/ys_display_medium"
android:textSize="@dimen/dp_16"
Заменить на style="@style/TextRegular16"

android:textColor="?attr/colorOnPrimary"

2024-07-13 18:03 UTC, lesOlesya commented on app/src/main/res/layout/item_vacancy.xml
> +        app:layout_constraintStart_toEndOf="@+id/ivLogo"
Заменить app:layout_constraintStart_toEndOf="@+id/ivLogo" на app:layout_constraintStart_toStartOf="@+id/tvVacancyName"

Удалить android:layout_marginStart="@dimen/dp_12"
        android:layout_marginBottom="@dimen/dp_16"
        
android:fontFamily="@font/ys_display_medium"
android:textSize="@dimen/font_16"
Заменить на style="@style/TextRegular16"

android:textColor="?attr/colorOnPrimary"

2024-07-13 18:03 UTC, lesOlesya commented on app/src/main/res/values-night/themes.xml
откат

2024-07-13 18:03 UTC, lesOlesya commented on app/src/main/res/values/colors.xml
откат

2024-07-13 18:03 UTC, lesOlesya commented on app/src/main/res/values/themes.xml
откат

2024-07-13 18:48 UTC, lesOlesya approved these changes

2024-07-15 12:26 UTC, KrokodilGenadiy reviewed
lgtm

2024-07-15 12:28 UTC, merged