Completed task
lesOlesya/YP-android-diploma-team5 pull request #41
Opened 2024-07-14 23:20 UTC by KrokodilGenadiy

2024-07-15 08:20 UTC, lesOlesya requested changes

2024-07-15 08:20 UTC, lesOlesya commented on app/src/main/res/values/strings.xml
> +    <string name="favorites">Избранное</string>
Эти строки уже были добавлены выше. Используй старые, пожалуйста

2024-07-15 08:20 UTC, lesOlesya commented on app/src/main/res/values/dimens.xml
> +    <dimen name="font_19">19sp</dimen>
На макетах вроде бы нет такого размера

2024-07-15 08:20 UTC, lesOlesya commented on app/src/main/res/layout/favourite_fragment.xml
> +        layout="@layout/not_found_placeholder"/>
Было бы хорошо, если бы во всё проекте плейсхолдеры добавлялись одинаково
Уже есть несколько экранов с одинаковым добавлением плейсхолдеров, поэтому используй, пожалуйста, этот метод
![image](https://github.com/user-attachments/assets/d828198e-a4af-40d6-94d7-ae9bddb65b8f)
![image](https://github.com/user-attachments/assets/ab4e6d03-240f-43aa-b516-7c3ff1a9182c)

2024-07-15 08:20 UTC, lesOlesya commented on app/src/main/java/ru/practicum/android/diploma/favourite/ui/FavoritesViewModel.kt
В задачу входит полная проработка фрагмента и вьюМодел
Тебе нужно замержить в свою ветку DIPLOMA-26 и DIPLOMA-34 и сделать полностью готовый экран Избранное(кроме индикации, это уже другое задание)

2024-07-16 16:02 UTC, KrokodilGenadiy commented on app/src/main/res/layout/favourite_fragment.xml
> +        layout="@layout/not_found_placeholder"/>
ок, использую этот стиль

2024-07-16 16:07 UTC, KrokodilGenadiy commented on app/src/main/res/values/strings.xml
> +    <string name="favorites">Избранное</string>
ок

2024-07-16 16:08 UTC, KrokodilGenadiy commented on app/src/main/res/values/dimens.xml
> +    <dimen name="font_19">19sp</dimen>
Так на макетах вообще размера текста нет, не знаю на как исправить

2024-07-16 16:08 UTC, KrokodilGenadiy commented on app/src/main/java/ru/practicum/android/diploma/favourite/ui/FavoritesViewModel.kt
ок

2024-07-17 04:34 UTC, lesOlesya approved these changes

2024-07-17 08:05 UTC, Vaaargr approved these changes

2024-07-17 11:10 UTC, merged